/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rent;

/**
 *
 * @author aunir
 */
public class Admin_viewAccount extends javax.swing.JFrame {

    /**
     * Creates new form Admin_viewAccount
     */
    public Admin_viewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pw_lbl1 = new javax.swing.JLabel();
        Z_homeBtn = new javax.swing.JButton();
        username_TXT = new javax.swing.JTextField();
        pw_lbl = new javax.swing.JLabel();
        myAcc_pwTXT = new javax.swing.JPasswordField();
        lblEmail_myAcc = new javax.swing.JLabel();
        emailMyAcc_TXT = new javax.swing.JTextField();
        lbl_editPword = new javax.swing.JLabel();
        deleteAcc_Btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Z] MY ACCOUNT");
        setLocation(new java.awt.Point(500, 95));
        setPreferredSize(new java.awt.Dimension(370, 526));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 526));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(198, 225, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pw_lbl1.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        pw_lbl1.setForeground(new java.awt.Color(66, 63, 63));
        pw_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pw_lbl1.setText("Profile Details");
        jPanel2.add(pw_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Z_homeBtn.setBackground(new java.awt.Color(252, 205, 146));
        Z_homeBtn.setFont(new java.awt.Font("Dubai Medium", 0, 15)); // NOI18N
        Z_homeBtn.setForeground(new java.awt.Color(66, 63, 63));
        Z_homeBtn.setText("Z");
        Z_homeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Z_homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z_homeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(Z_homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        username_TXT.setBackground(new java.awt.Color(255, 255, 255));
        username_TXT.setFont(new java.awt.Font("Dubai Medium", 0, 15)); // NOI18N
        username_TXT.setForeground(new java.awt.Color(66, 63, 63));
        username_TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_TXT.setBorder(null);
        jPanel1.add(username_TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 30));

        pw_lbl.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        pw_lbl.setForeground(new java.awt.Color(66, 63, 63));
        pw_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pw_lbl.setText("Password");
        jPanel1.add(pw_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        myAcc_pwTXT.setBackground(new java.awt.Color(255, 255, 255));
        myAcc_pwTXT.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        myAcc_pwTXT.setForeground(new java.awt.Color(66, 63, 63));
        myAcc_pwTXT.setBorder(null);
        jPanel1.add(myAcc_pwTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, 30));

        lblEmail_myAcc.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblEmail_myAcc.setForeground(new java.awt.Color(66, 63, 63));
        lblEmail_myAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail_myAcc.setText("Email");
        jPanel1.add(lblEmail_myAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        emailMyAcc_TXT.setBackground(new java.awt.Color(255, 255, 255));
        emailMyAcc_TXT.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        emailMyAcc_TXT.setForeground(new java.awt.Color(66, 63, 63));
        emailMyAcc_TXT.setBorder(null);
        jPanel1.add(emailMyAcc_TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 180, 30));

        lbl_editPword.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lbl_editPword.setForeground(new java.awt.Color(66, 63, 63));
        lbl_editPword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_editPword.setText("Edit password");
        lbl_editPword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_editPwordMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_editPword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        deleteAcc_Btn.setBackground(new java.awt.Color(255, 105, 97));
        deleteAcc_Btn.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        deleteAcc_Btn.setForeground(new java.awt.Color(255, 255, 255));
        deleteAcc_Btn.setText("Delete account");
        deleteAcc_Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(deleteAcc_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 180, 10));

        jButton1.setBackground(new java.awt.Color(252, 205, 146));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(66, 63, 63));
        jButton1.setText("LOG OUT");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Z_homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z_homeBtnActionPerformed
        Admin_Home_Page goHome = new Admin_Home_Page();
        goHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Z_homeBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin_Login logOut = new Admin_Login();
        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_editPwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editPwordMouseClicked
        Admin_ForgotPW_Page changePW = new Admin_ForgotPW_Page();
        changePW.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_editPwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_viewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_viewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_viewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_viewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_viewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Z_homeBtn;
    private javax.swing.JButton deleteAcc_Btn;
    private javax.swing.JTextField emailMyAcc_TXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEmail_myAcc;
    private javax.swing.JLabel lbl_editPword;
    private javax.swing.JPasswordField myAcc_pwTXT;
    private javax.swing.JLabel pw_lbl;
    private javax.swing.JLabel pw_lbl1;
    private javax.swing.JTextField username_TXT;
    // End of variables declaration//GEN-END:variables
}
