/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rent;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aunir
 */
public class Admin_genReport extends javax.swing.JFrame {

    private int row, column;
    /**
     * Creates new form Admin_genReport
     */
    public Admin_genReport() {
        initComponents();
        
        //set size of column
        report_table.getColumnModel().getColumn(0).setPreferredWidth(50);
        report_table.getColumnModel().getColumn(5).setPreferredWidth(80);
        report_table.getColumnModel().getColumn(6).setPreferredWidth(80);
        report_table.getColumnModel().getColumn(7).setPreferredWidth(80);
        report_table.getColumnModel().getColumn(8).setPreferredWidth(80);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_pageName = new javax.swing.JLabel();
        btn_toHome = new javax.swing.JButton();
        date_from = new com.toedter.calendar.JDateChooser();
        date_to = new com.toedter.calendar.JDateChooser();
        lbl_sales = new javax.swing.JLabel();
        lbl_totalAmountSales = new javax.swing.JLabel();
        btn_generate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        report_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Z] REPORT");
        setLocation(new java.awt.Point(325, 95));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(198, 225, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_pageName.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lbl_pageName.setForeground(new java.awt.Color(60, 63, 65));
        lbl_pageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pageName.setText("ZEBRAX SALES REPORT");
        jPanel2.add(lbl_pageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 10));

        btn_toHome.setBackground(new java.awt.Color(252, 205, 146));
        btn_toHome.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btn_toHome.setForeground(new java.awt.Color(60, 63, 65));
        btn_toHome.setText("HOME");
        btn_toHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_toHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_toHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        date_from.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 140, -1));

        date_to.setDateFormatString("yyyy-MM-d");
        jPanel1.add(date_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 140, -1));

        lbl_sales.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lbl_sales.setForeground(new java.awt.Color(60, 63, 65));
        lbl_sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sales.setText("TOTAL SALES THIS MONTH:");
        jPanel1.add(lbl_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        lbl_totalAmountSales.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lbl_totalAmountSales.setForeground(new java.awt.Color(60, 63, 65));
        lbl_totalAmountSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_totalAmountSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 120, 20));

        btn_generate.setBackground(new java.awt.Color(252, 205, 146));
        btn_generate.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btn_generate.setForeground(new java.awt.Color(60, 63, 65));
        btn_generate.setText("Generate");
        btn_generate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 70, 30));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("From");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 20));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 63, 65));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("To");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 20));

        report_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Created", "Car Plate", "Start Date", "End Date", "Email", "Firstname", "Lastname", "IC No", "Total Rental", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(report_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 230, 800, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_toHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toHomeActionPerformed
        Admin_Home_Page goHomePage = new Admin_Home_Page();
        goHomePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_toHomeActionPerformed

    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateActionPerformed

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        if ((date_from.getDate() == null) || (date_to.getDate() == null) )
        {
            JOptionPane.showMessageDialog(this, "Date is required.");
            return;
        }
    
        String salesFrom = dateFormat.format(date_from.getDate());
        String salesTo = dateFormat.format(date_to.getDate());
        
        
        String salesFP = "src/main/java/database/rental_history.txt";
        File salesFile = new File(salesFP);

        DefaultTableModel salesTable = (DefaultTableModel)report_table.getModel();
        salesTable.setRowCount(0);
        try {
            BufferedReader br = new BufferedReader(new FileReader(salesFile));
            String s="";
            while ((s=br.readLine()) != null) {
                String data[] = new String[7];
                data = s.split(",");

                String booking_date = data[1].split(" ")[0];
                if((salesFrom.compareTo(booking_date)<=0) && (salesTo.compareTo(booking_date)>=0))
                {
                    Vector v2 = new Vector();
                    for (int i = 0; i < data.length; i++)
                    {
                        v2.add(data[i].trim());
                    }
                    salesTable.addRow(v2);
                }
            }
        } catch (Exception e) {
            System.out.println("Error");
        }
        if (salesTable.getRowCount()<=0) {
            JOptionPane.showMessageDialog(this, "No any booking found.");
        }
    }//GEN-LAST:event_btn_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_genReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_genReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_genReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_genReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Admin_genReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generate;
    private javax.swing.JButton btn_toHome;
    private com.toedter.calendar.JDateChooser date_from;
    private com.toedter.calendar.JDateChooser date_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_pageName;
    private javax.swing.JLabel lbl_sales;
    private javax.swing.JLabel lbl_totalAmountSales;
    private javax.swing.JTable report_table;
    // End of variables declaration//GEN-END:variables
}
