/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rent;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author aunir
 */
public class Admin_Login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_logo
     */
    public Admin_Login() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo_pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        user_logo = new javax.swing.JLabel();
        password_logo = new javax.swing.JLabel();
        ForgotPassLbl = new javax.swing.JLabel();
        SignInBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZEBRAX");
        setLocation(new java.awt.Point(325, 95));
        setSize(new java.awt.Dimension(669, 441));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(346, 441));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 63, 63));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ZEBRAX");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 63, 63));
        jLabel1.setText("zzzzZzzzzZzzzzzZzzzzzZzzzzzZzzzzzZzzzzZzzzzZzzzzZzz");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, 20));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 63, 63));
        jLabel4.setText("zzzzZzzzzZzzzzzZzzzzzZzzzzzZzzzzzZzzzzZzzzzZzzzzZzz");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 340, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(198, 225, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_pic.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        logo_pic.setForeground(new java.awt.Color(249, 255, 245));
        logo_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_pic.setText("Hey, welcome back!");
        logo_pic.setToolTipText("");
        jPanel2.add(logo_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 190, 30));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 255, 245));
        jLabel2.setText("Sign in to your account");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 137, -1, -1));

        username.setBackground(new java.awt.Color(198, 225, 176));
        username.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(249, 255, 245));
        username.setText("Username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 187, 143, 30));

        password.setBackground(new java.awt.Color(198, 225, 176));
        password.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(249, 255, 245));
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 260, 143, 30));

        jSeparator1.setForeground(new java.awt.Color(249, 255, 245));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 217, 180, -1));

        jSeparator2.setForeground(new java.awt.Color(249, 255, 245));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 290, 180, -1));
        jPanel2.add(user_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 187, 29, 29));
        jPanel2.add(password_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 260, 35, 28));

        ForgotPassLbl.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        ForgotPassLbl.setForeground(new java.awt.Color(249, 255, 245));
        ForgotPassLbl.setText("Forgot Password? ");
        ForgotPassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassLblMouseClicked(evt);
            }
        });
        jPanel2.add(ForgotPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 293, -1, -1));

        SignInBtn.setBackground(new java.awt.Color(252, 205, 146));
        SignInBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(66, 63, 63));
        SignInBtn.setText("Sign In");
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 357, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 63, 63));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Z");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 0, 330, 441));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        username.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setText("");
 
    }//GEN-LAST:event_passwordFocusGained

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        
        
        //to get the username and password
         String username = this.username.getText();
         String password = this.password.getText();
        
        //find file to check the name inside the file
        try {
            File admin = new File("D:\\OODJ_ASSIGNMENT\\Zebrax\\src\\main\\java\\admin_database\\admin_login.txt");
            Scanner scan = new Scanner(admin);
            scan.useDelimiter("[,\n]"); //pattern stop at comma or newline
            
            while(scan.hasNext()) //to check if there's still non white space char
            {
                String user = scan.next(); //read the next thing until it reached ',' or newline
                String pw = scan.next();
                
                if(username.trim().equals(user.trim()) && password.trim().equals(pw.trim())) // to see if it matches
                {
                    JOptionPane.showMessageDialog(null, "Hey hi, it's good to have you back!");
                    Admin_Home_Page adminPage; //pop new page
                    adminPage = new Admin_Home_Page();
                    adminPage.setVisible(true);
                    this.dispose(); //close this window
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Credentials");
                }
            }    
            
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(null,"Error, please report to admin!");
        }
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void ForgotPassLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassLblMouseClicked
                    Admin_ForgotPW_Page ForgotPW; //pop new page
                    ForgotPW = new Admin_ForgotPW_Page();
                    ForgotPW.setVisible(true);
                    this.dispose(); //close this window
    }//GEN-LAST:event_ForgotPassLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgotPassLbl;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo_pic;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_logo;
    private javax.swing.JLabel user_logo;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    
}
